cookie:
  expiry_days: 100
  key: thisisauthenticatorkey
  name: auth
creatine:
  added_today: 0
  amount: 20
  date_refreshed: 2024-12-04
credentials:
  usernames:
    birdman:
      email: email@email.com
      first_name: Rishi
      last_name: Gupta
      logged_in: false
      password: Password
      password_hint: pfft
      roles: null
